services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "YtReWq4321"
      MYSQL_DATABASE: "virtd"
      MYSQL_USER: "app"
      MYSQL_PASSWORD: "QwErTy1234"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile.python
    restart: always
    environment:
      DB_HOST: "mysql"
      DB_USER: "app"
      DB_PASSWORD: "QwErTy1234"
      DB_NAME: "virtd"
    depends_on:
      - mysql
    networks:
      - backend

  haproxy:
    image: haproxy:2.4
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./Haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:rw
    depends_on:
      - app
    networks:
      - backend

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "8090:80"
    volumes:
      - ./nginx/ingress/default.conf:/etc/nginx/conf.d/default.conf:rw
    depends_on:
      - haproxy
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
    driver: bridge
