version: '3.8'

services:
  web:
    build:
      context: .  # Укажите папку с Dockerfile.python
      dockerfile: Dockerfile.python
    
    # image: cr.yandex/<идентификатор_регистра>/<название_репозитория>:<версия>
    container_name: web
    restart: always
    networks:
      backend:
        ipv4_address: 172.20.0.5
    environment:
      DB_HOST: db           # Имя сервиса MySQL
      DB_PORT: 3306
      DB_USER: app_user     # Пользователь базы данных
      DB_PASS: very_secure_password
      DB_NAME: example_db   # Название базы данных

  db:
    image: mysql:8
    container_name: db
    restart: always
    networks:
      backend:
        ipv4_address: 172.20.0.10
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: example_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: very_secure_password

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
